name: Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Set up Git user
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Generate changelog
      run: |
        # Check if CHANGELOG.md exists; create it if it doesn't
        if [ ! -f CHANGELOG.md ]; then
            touch CHANGELOG.md
        fi

        # Fetch all tags and latest changes
        git fetch --tags
        git pull origin main

        # Grab latest tag and generate change log
        latest_tag=$(git describe --tags --abbrev=0)

        # Generate the changelog
        git log --pretty=format:"* [%h](https://github.com/andrewendlinger/testdata/commit/%H) - %s" $latest_tag..HEAD > CHANGELOG.md

        # Commit changelog
        git add CHANGELOG.md
        git commit -m "Updated changelog to $latest_tag"
        git push origin HEAD:main
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

