name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bump version
        run: |
          current_version=$(<version.txt)
          IFS='.' read -r -a version_parts <<< "$current_version"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}
          new_version="$major.$minor.$((patch + 1))"
          echo "$new_version" > version.txt
          echo "Bumped version to $new_version"

          # Create a tag for this version
          git tag "v$new_version"
          git push origin "v$new_version"

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.txt
          git commit -m "Bump version to $new_version"
          git push
