name: Bump Version and Push Tag

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --local credential.helper store  # Store credentials temporarily

      - name: Bump version and push tag
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
            bash ./scripts/version_bump.sh

  generate-changelog:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --local credential.helper store  # Store credentials temporarily

      - name: Generate changelog
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
            bash ./scripts/generate_changelog.sh