name: Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Set up Git user
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Run changelog script
      run: ./generate_changelog.sh
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Changelog
      uses: actions/upload-artifact@v2
      with:
        name: CHANGELOG.md
        path: CHANGELOG.md
